Add devise
AbbyNyakara/Rails_BlogApp pull request #10
Opened 2022-10-19 07:27 UTC by AbbyNyakara

In this PR, I achieved the following: 

Remove current_user method in ApplicationController, devise will provide us with one.
[Install and setup devise](https://github.com/heartcombo/devise#getting-started).
Can register a new user.
User logs in with a combination of email and password.
Hashed password should be stored in the database.
Ask for confirmation of email.
Can reset password.

P/S My partner is unresponsive and im currently unable to work with him.

2022-10-19 07:55 UTC, Mihndim2020 requested changes
### Hi @AbbyNyakara, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments under the review._

### I will leave these comments here since you did not make any changes in your `user.rb` file for this `PR`. 
- [ ] Please make sure you implement the following [requirements ](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md)before you resubmit for another review.
 - [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
    - Can register a new user.
    - User logs in with a combination of email and password.
    - Hashed password should be stored in the database.
    - Ask for confirmation of email.
    - Can reset password.
    - [Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and your styling.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 09:10 UTC, KayLemba approved these changes
Hi @AbbyNyakara ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Invalid Code Review Request

You have submitted a project, that doesn't have the required changes for this milestone. Kindly make sure that the PR submitted has the required features implemented.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
Cheers and Happy coding! 👏 👏 👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2022-10-19 10:50 UTC, prolajumokeoni requested changes
Hi @AbbyNyakara, 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used 
✔️  Good PR title and Description

 ## Required Changes ♻️

- [ ] Kindly setup Devise following the instructions, please check the [getting started](https://github.com/heartcombo/devise#getting-started) section on the Devise documentation  also the `gem 'devise'` is missing in your Gemfile, please ensure you do the setup correctly, I advise you go through the comment by [previous reviewer
](https://github.com/AbbyNyakara/Rails_BlogApp/pull/10#pullrequestreview-1147030501) again.
- Please make sure that you achieve all the goals from the [project requirement
](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#project-requirements)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 06:41 UTC, FrederickMih requested changes
Hi @AbbyNyakara, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights :green_circle: 

- Correct Gitflow :heavy_check_mark: 
- No Linter error :heavy_check_mark: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 06:41 UTC, FrederickMih commented on app/views/devise/sessions/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] Based on the requirements of this project, the views in devise for the registration and login should be modified to match the wireframes and their styling.


|  Yours  |  Wireframe   | 
|  ---  |  --- |  
|  ![Screenshot from 2022-10-20 07-26-38](https://user-images.githubusercontent.com/63087491/196872415-1dc20916-4356-4032-be70-4dd7435b40b3.png)  | ![Screenshot from 2022-10-20 07-26-00](https://user-images.githubusercontent.com/63087491/196872317-02b8d2a3-bc01-4364-a405-58c2da00eebe.png)  |

Let's kindly fix this issue.

2022-10-20 06:41 UTC, FrederickMih commented on app/views/devise/sessions/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] After registering into your app, I didn't receive confirmation information. I got the console error on the screenshot below:


![Screenshot from 2022-10-20 07-34-45](https://user-images.githubusercontent.com/63087491/196873730-d3f1fdc5-3ef5-467f-b28b-9455544c37dc.png)

Please let's fix :wrench: it so that I can be able to register and log into your app successfully.

2022-10-20 10:03 UTC, AbbyNyakara commented on app/views/devise/sessions/new.html.erb
> +<%= render "devise/shared/links" %>
done

2022-10-20 10:03 UTC, AbbyNyakara commented on app/views/devise/sessions/new.html.erb
> +<%= render "devise/shared/links" %>
done

2022-10-20 10:15 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @AbbyNyakara,

✔️ Integration of devise

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 10:17 UTC, merged