add project controllers
AbbyNyakara/Rails_BlogApp pull request #4
Opened 2022-10-03 12:38 UTC by AbbyNyakara

In this PR, I created the controllers for the post and the users. 
For now, the paths will display dummy text for each of the paths.

2022-10-03 13:09 UTC, prolajumokeoni requested changes
Hi @AbbyNyakara, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used
✔️  Good PR title and Description



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-03 13:09 UTC, prolajumokeoni commented on config/routes.rb
> +  get 'users/show'
- [ ] Kindly create routes for users and posts index and show pages correctly, this helps you make sure you don't expose unnecessary routes. Currently, only the user's index and show routes are created it would be better to loop through the users routes to know which user is  creating a post, see example below ⬇️   

 ````
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
````

2022-10-04 10:30 UTC, AbbyNyakara commented on config/routes.rb
> +  get 'users/show'
@prolajumokeoni , would you please review my code if youre able to?

2022-10-04 11:10 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @AbbyNyakara 

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Gitflow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-05 06:50 UTC, merged